export const posts = [
  {
    _id: "5ff18dd9bb19da8432468a31",
    title: "incididunt laboris eu anim dolore nisi",
    picture: "https://picsum.photos/640/320",
    thumbnail: "https://picsum.photos/500",
    slug: "makaba",
    teaser:
      "Culpa magna cillum exercitation non commodo sit. Labore ex irure consequat proident adipisicing amet ex consequat do sint adipisicing. Voluptate minim velit irure commodo fugiat excepteur duis adipisicing ea dolor ipsum ea aliquip anim. Culpa minim anim velit sunt nulla culpa est veniam occaecat nulla veniam nulla officia. Irure commodo do sit ullamco pariatur esse cillum duis. Qui eu in enim officia in id deserunt Lorem fugiat laborum velit occaecat aliquip amet. Laboris officia proident cillum id anim duis officia proident eu ullamco cupidatat incididunt veniam.\r\n",
    tags: ["tech", "programming"],
    author: "Herrera Grimes",
    mtr: 10,
    created_at: "Sat Jan 13 2018 13:13:18 GMT+0700 (Western Indonesia Time)",
  },
  {
    _id: "5ff18dd9c98b977dbff51b13",
    title: "consequat reprehenderit laborum eu cillum sit",
    picture: "https://picsum.photos/640/320",
    thumbnail: "https://picsum.photos/501",
    slug: "makaba",
    teaser:
      "Tempor excepteur aute commodo Lorem magna. Dolor elit qui nulla nulla id aliqua nisi occaecat aute irure magna. Sunt incididunt in ipsum ut laborum elit sit eu in ea. Amet reprehenderit culpa magna culpa. Duis laborum quis consectetur ad pariatur voluptate deserunt consectetur nostrud.\r\n",
    tags: ["tech", "opiny", "programming"],
    author: "Henrietta Burke",
    mtr: 6,
    created_at: "Mon Jun 29 2015 01:11:32 GMT+0700 (Western Indonesia Time)",
  },
  {
    _id: "5ff18dd91049a67c57cf6762",
    title: "voluptate minim minim proident sint culpa",
    picture: "https://picsum.photos/640/320",
    thumbnail: "https://picsum.photos/502",
    slug: "makaba",
    teaser:
      "Lorem ipsum laboris ut excepteur qui excepteur in tempor dolor et pariatur in nisi aliquip. Eiusmod est ipsum elit in Lorem qui fugiat amet culpa duis culpa tempor. Eiusmod pariatur occaecat sunt commodo exercitation quis ipsum laboris.\r\n",
    tags: ["tech"],
    author: "Short Walter",
    mtr: 15,
    created_at: "Sun Mar 04 2018 20:41:32 GMT+0700 (Western Indonesia Time)",
  },
  {
    _id: "5ff18dd9fcd66aa17c421cf8",
    title: "enim cupidatat do exercitation officia ipsum",
    picture: "https://picsum.photos/640/320",
    thumbnail: "https://picsum.photos/503",
    slug: "makaba",
    teaser:
      "Eiusmod veniam sit sint occaecat quis in occaecat ex. Ut elit velit veniam nostrud ad pariatur aliqua. Cupidatat cupidatat enim eu dolore esse quis mollit labore sint exercitation. Exercitation labore officia culpa duis consectetur laborum pariatur. Consequat veniam aliqua id ullamco nisi aliquip labore. Aliqua laborum amet anim fugiat occaecat.\r\n",
    tags: ["story"],
    author: "Ayala Serrano",
    mtr: 10,
    created_at: "Sun Dec 13 2015 19:36:02 GMT+0700 (Western Indonesia Time)",
  },
  {
    _id: "5ff18dd9fb939b3769dea169",
    title: "aliqua esse aute elit ex elit",
    picture: "https://picsum.photos/640/320",
    thumbnail: "https://picsum.photos/504",
    slug: "makaba",
    teaser:
      "Duis nulla elit id minim quis reprehenderit mollit culpa. Exercitation consequat ut veniam dolor dolor ad et eu. Minim laborum sint irure labore. Proident fugiat aliquip occaecat labore mollit ut deserunt veniam duis ad culpa magna amet anim. Mollit velit ea quis velit do.\r\n",
    tags: ["feature", "opiny"],
    author: "Benton Hale",
    mtr: 11,
    created_at: "Fri Jun 17 2016 02:27:25 GMT+0700 (Western Indonesia Time)",
  },
  {
    _id: "5ff18dd9717766c8355dfdfe",
    title: "duis laboris pariatur aliqua dolore labore",
    picture: "https://picsum.photos/640/320",
    thumbnail: "https://picsum.photos/505",
    slug: "makaba",
    teaser:
      "Occaecat in veniam in ut laborum fugiat aute sunt ad eiusmod. Cupidatat eu reprehenderit est est consectetur Lorem duis ea. Mollit nisi quis ut nulla. Dolore consectetur eu ad ea quis nisi voluptate laboris dolore. Aliquip et enim irure Lorem.\r\n",
    tags: ["tech", "programming"],
    author: "Jannie Benton",
    mtr: 16,
    created_at: "Thu May 07 2020 23:52:54 GMT+0700 (Western Indonesia Time)",
  },
  {
    _id: "5ff18dd9c6b370c414eed100",
    title: "esse officia ea exercitation eiusmod do",
    picture: "https://picsum.photos/640/320",
    thumbnail: "https://picsum.photos/506",
    slug: "makaba",
    teaser:
      "Duis reprehenderit deserunt exercitation et elit elit velit commodo cupidatat labore. Culpa aliquip in ex commodo consectetur tempor culpa velit velit ex sint. Fugiat non reprehenderit labore proident nostrud proident qui nostrud incididunt sunt eu sunt. Nulla commodo do consectetur veniam aliquip incididunt fugiat incididunt ullamco esse. Voluptate proident ut sunt incididunt. Quis anim ipsum aliqua ullamco elit nisi amet enim ut.\r\n",
    tags: ["tech", "opiny"],
    author: "Osborn Brock",
    mtr: 5,
    created_at: "Fri Mar 20 2015 05:26:01 GMT+0700 (Western Indonesia Time)",
  },
  {
    _id: "5ff18dd9ec9dfb80067b191b",
    title: "excepteur aliquip eiusmod eiusmod qui exercitation",
    picture: "https://picsum.photos/640/320",
    thumbnail: "https://picsum.photos/507",
    slug: "makaba",
    teaser:
      "Sit dolor ipsum sunt tempor dolore mollit ut reprehenderit nulla pariatur do cupidatat ipsum aute. Sint ipsum voluptate id sint esse amet officia ad. Voluptate cillum cupidatat tempor ullamco ea irure. Magna aliqua quis mollit officia non nisi. Nisi in esse sint velit ad. Nisi sit mollit aute magna aliqua aliqua incididunt labore velit minim elit Lorem quis sit. Adipisicing laborum aute reprehenderit officia fugiat ex tempor.\r\n",
    tags: ["opiny", "story"],
    author: "Pearlie Barron",
    mtr: 18,
    created_at: "Fri May 25 2018 03:01:47 GMT+0700 (Western Indonesia Time)",
  },
  {
    _id: "5ff18dd919316226b5e14614",
    title: "enim dolor nisi excepteur deserunt sit",
    picture: "https://picsum.photos/640/320",
    thumbnail: "https://picsum.photos/508",
    slug: "makaba",
    teaser:
      "Voluptate laborum ullamco voluptate sunt laboris et est do id aute. Ipsum veniam deserunt officia consequat sunt duis tempor proident irure do nisi. Enim tempor est occaecat dolore non occaecat laboris dolore sit. Mollit consequat in quis est exercitation dolor ad consequat cillum aliquip. Excepteur duis commodo mollit aliqua nostrud deserunt aliqua incididunt.\r\n",
    tags: ["programming"],
    author: "Velasquez Todd",
    mtr: 5,
    created_at: "Thu Mar 09 2017 16:43:31 GMT+0700 (Western Indonesia Time)",
  },
  {
    _id: "5ff18dd9bb25a13553bc6faa",
    title: "qui magna tempor tempor excepteur laboris",
    picture: "https://picsum.photos/640/320",
    thumbnail: "https://picsum.photos/509",
    slug: "makaba",
    teaser:
      "Dolore commodo minim pariatur enim pariatur. Labore pariatur ea tempor cillum culpa do adipisicing ullamco consectetur aliqua qui aute id minim. Veniam occaecat aute velit dolore nisi laborum qui Lorem laborum magna excepteur ipsum aute. Commodo deserunt veniam adipisicing officia duis sint sit culpa veniam ut pariatur cillum fugiat.\r\n",
    tags: ["research", "tech"],
    author: "Pat Riley",
    mtr: 8,
    created_at: "Sun Apr 24 2016 17:20:58 GMT+0700 (Western Indonesia Time)",
  },
];
